[package]
name = "forwarder-raw"
version = "0.0.0"
authors = ["Test Author"]
edition = "2018"
publish = false

[lib]
path = "src/forwarder_raw.rs"

[features]
wasm-output-mode = [
    "testnumbat-wasm-node",
]
wasm-output-mode-managed-ei = [
    "wasm-output-mode",
]
wasm-output-mode-unmanaged-ei = [
    "wasm-output-mode",
    "testnumbat-wasm-node/unmanaged-ei"
]

[dependencies.testnumbat-wasm]
version = "0.0.2"
path = "../../../../testnumbat-wasm"
features = ["derive", "cb_closure_managed_deser"]

[dependencies.testnumbat-wasm-node]
version = "0.0.2"
path = "../../../../testnumbat-wasm-node"
optional = true

[dev-dependencies.testnumbat-wasm-debug]
version = "0.0.2"
path = "../../../../testnumbat-wasm-debug"
