[package]
name = "factory-abi"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.order-book-factory]
path = ".."

[dependencies.testnumbat-wasm]
version = "0.0.2"
path = "../../../../../testnumbat-wasm"

[dependencies.testnumbat-wasm-debug]
version = "0.0.2"
path = "../../../../../testnumbat-wasm-debug"
